---
- name: k8s cluster setup
  hosts: all
  become: yes
  tasks: 
    - name: install docker
      import_tasks: tasks/docker.yml

    - name: install k8s
      import_tasks: tasks/k8s.yml

- name: k8s master conf
  hosts: masters
  become: yes
  tasks:
    - name: k8s master configuration
      import_tasks: tasks/k8s_master.yml
      
- name: k8s node conf
  hosts: nodes
  become: yes
  tasks:
    - name: node configuration
      import_tasks: tasks/k8s_node.yml