---
  - name: Disable SWAP
    shell: |
      swapoff -a

  - name: Disable SWAP in fstab
    replace:
      path: /etc/fstab
      regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
      replace: '# \1'

  - name: Create an empty file for K8S sysctl parameters
    copy:
      content: ""
      dest: /etc/sysctl.d/99-kubernetes-cri.conf
      force: no

  - name: Configure sysctl parameters for K8S
    lineinfile:
      path: /etc/sysctl.d/99-kubernetes-cri.conf
      line: "{{ item }}"
    with_items:
      - "net.bridge.bridge-nf-call-iptables  = 1"
      - "net.ipv4.ip_forward                 = 1"
      - "net.bridge.bridge-nf-call-ip6tables = 1"

  - name: Apply sysctl parameters
    command: sysctl --system

  - name: Install APT Transport HTTPS
    apt:
      name: apt-transport-https
      state: present

  - name: Add Kubernetes apt-key
    get_url:
      url: https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key
      dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc
      mode: "0644"
      force: true

  - name: Add Kubernetes APT repository
    apt_repository:
      repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /"
      state: present
      update_cache: yes

  - name: Install Kubelet
    apt:
      name: kubelet=1.29.*
      state: present
      update_cache: true

  - name: Install Kubeadm
    apt:
      name: kubeadm=1.29.*
      state: present

  - name: Enable the Kubelet service
    service:
      name: kubelet
      enabled: yes

  - name: Load br_netfilter kernel module
    modprobe:
      name: br_netfilter
      state: present

  - name: Set bridge-nf-call-iptables
    sysctl:
      name: net.bridge.bridge-nf-call-iptables
      value: 1

  - name: Set ip_forward
    sysctl:
      name: net.ipv4.ip_forward
      value: 1
